# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoBookTeacher < Formula
  desc "find teacher's lesson"
  homepage "https://github.com/hiromaily/go-book-teacher"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hiromaily/go-book-teacher/releases/download/v1.0.0/go-book-teacher_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "1f0a9b65e1fa94df384c8955e12acdadee028c19b60f1abc879ada3cc0266c2b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/hiromaily/go-book-teacher/releases/download/v1.0.0/go-book-teacher_1.0.0_Linux_x86_64.tar.gz"
    sha256 "9655858c810e0a156cf9941543de56e4ead3aa37378224e209ae33bd25696bb2"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/hiromaily/go-book-teacher/releases/download/v1.0.0/go-book-teacher_1.0.0_Linux_arm64.tar.gz"
    sha256 "fef3cb1874137969789eaeb7cc1ffa0fff7359d2c0eb49e513bff1303b0b4e45"
  end

  def install
    bin.install "book"
  end

  test do
    system "#{bin}/bool -v"
  end
end
