# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoBookTeacher < Formula
  desc "find teacher's lesson"
  homepage "https://github.com/hiromaily/go-book-teacher"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hiromaily/go-book-teacher/releases/download/v1.0.0/go-book-teacher_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "a058665aa4fc4003692d1b87e53d2f9e230da7cba89ac703da296a59684f8b71"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/hiromaily/go-book-teacher/releases/download/v1.0.0/go-book-teacher_1.0.0_Linux_x86_64.tar.gz"
    sha256 "ffe64fe4283c425a0240efb321b5560f3581704c148cba5b11c3c8bcc53b7fec"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/hiromaily/go-book-teacher/releases/download/v1.0.0/go-book-teacher_1.0.0_Linux_arm64.tar.gz"
    sha256 "0cc941a42b6c0fecd137cd585b84cb5bc966de58caa2fc0ec5723ab0f1c02cf8"
  end

  def install
    bin.install "book-teacher"
  end

  test do
    system "#{bin}/book-teacher -v"
  end
end
